{{- $tlsEnabled := .Values.tls.enabled -}}
{{- if .Values.global -}}
{{- if .Values.global.tlsEnabled -}}
{{ $tlsEnabled = true }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "fusion-argo-commons"
data:
  postModelTag: "{{ .Values.image.postModelTag | default .Values.image.tag }}"
  sparkSolrEtl: "{{ .Values.image.sparkSolrEtlTag | default .Values.image.tag }}"
  transferBlobsTag: "{{ .Values.image.transferBlobsTag | default .Values.image.tag }}"
  datapullerTag: "{{ .Values.image.datapullerTag | default .Values.image.tag }}"
  workflowUtilitiesTag: "{{ .Values.image.utilitiesTag | default .Values.image.tag }}"
